dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: "vSbeXDyjUHHT0X0Nc2m860oYRTYnKyocAKwlE/1mQAf7+1OxDNPCkjkjzDPK8s8TdwrE4m2kAQHjXS40TwWAKBovv7RdZRAYC6nJHdUt5RZLV62QZzhXqdOnpMMtXcixYRAR1tU61b1nMB/u+6cujGSEdaHQPu1hhKEbiedfAX2h4GnAFBMxNKe+3aG0xmdPmF/2cAqVTj5HvOybyhlU368Nlbk3/OLWBzFaTUHchikLtE01L2T0Goj4gOYSOib7b7iwBhbuL0+O7DMInlyGBLhGG4feJN1SC2JNFGyaKLOF2tEbiVviGRnt8pEnnkKwDTNZwBmc2yQHr8jYkiY0xF7yZiDQTocGxxpDX2alFUDBnysHLa92YU6CYUC3vxHC2mx9VACHhst+skckYk2rTkWm6cBPZbnq2ZiJOf1tqMyaMothocIVnaPjpmuf4Ujwmsz4fZDzriBMIKJdN0boA0IW/bYgieXoOlUrU99HHzcnTdr/VE1k7KyUQxUxBGnkfbipMQNcWbRh/bpUuco7hqknBEE5fMFMYYW8yfeyvTjkIDFTYNWLf9CJjKpQ5gonbCB7BDJT3PObVO0I6Haq33pv/1Ihdg9Rvh6KY4EuniPQbyef631eRF7zDSlqH0BtZI5NTPKzaY95xPHlOvJnNKWuLo/OjJhmPOAmX/myLag="
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh -DexcludeGroupIds=uk.gov.justice.utils"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
env:
  global:
  - secure: pa6Q7MxIAik48OmheiwDEh+iKUIzzRCywPjM2cYXxHtcDTICxuzLDZZwBHMzrg/4FCN+Yeqn2eD8FvYYp98+62uXgcRfccxk/W2X3Z2NDnn220s9QMQIStDeOGIiWG+26j8P7cDKgyMHvqlo+mXmL3is9YgQujW6pGc9neybiqOlW9V8jvs1SvGOKF2e0YZ78gLPp4HDiivGq2FhZ3nRE/f7QQGvGGtslLIu5XOOgCXtlpEloQBHQHpH4feG3iXBS5k8dgOBLMV8DSzZO5QViD1iy1WjqTbuaUFxqOCKnjmukXWyU/Le/moG9c1eMulRTk4Naoj6XDb/IinX5TA6xOGJ7GoqhXC0ysQCRASbbW1Dh9D4YZ36EpedmOHD4WZum4PsEwGreBhK0hFyALnmagiqCJnzdyr1LjLbigTLu8hB+NQrL8GnNyGlZDnLzTJ5k3fJYuKJmtlq9ithqyerq3sjnByoEl5p2UIrL4Nq8ETuaglFEM0gDyZ1x/q4OcOsXqBk6KeQhyJW/2JjO7k/rfnZluzdzPnFJH6emZrzBduTzFyya5G/VILAO/PYPVIMld5/kDYQ/T45159tDVdSWeeR+C39QpXO7mUXR8JIIbDCsVsvyyBDsta4eZ0TcRsJQBtSuVbLPPyipd/TFHrfeT/URV+EbQApUbPd7n0nTr0=
  - secure: CSffdoX2/E/GDV0X+iZpQ0A25k0eWOo0fzMr0dqg3HZ47LgC7tZSh11hFsVkBMScRTR+y8Dp38KdGxKYzHdxuaLIH01cegv+RjE6MOz9jSiQ99hV0eCGbRGzLEAr95kiXqxkESAvTOKf3DPqdOoWjRUKyVnTDF9dfXYu0STKT48ISgid4O6czMUkTDwvQACkDAWZpYwwTCnMoDT/vCIjy/BSGa8dgOE3izE9YigHsfWrR7eMPAKo+p+3m0113VmfQG/T/tETMtMzYGiL7l5EJRzvd4ARqK+ornpHFoM9bEBSMovthLOv5lMRWnNXBnlcRl8xHuDFt2jTprbkoXusC/fDwqec8PD497mVxgx+CM4+KazDvobLXohUbTUgOa3c4ok8GIYVPs7yvzBd8YDvec9lQHcW3QWIaX2id2WBc0NJ5KkFpFtMNovkeLTKdarIg9hVxME8C66GNtavAapP6+uWLYND9d6YV9mSRnNOsJmxO2JfMdHzSPtvXdnBhMTyaBprsZa6XGJhSRSGLswCwdxkZ3dpVf7JCtqZV62GKOWznya2fT6CwBNOGHgV/4HjtWVniQX0SavatS+zV43NfW4NADk4OsljbJ8HLknfHsGBOG9aUG3FYpP5Y2wbVF60MfirLKkhTqdb7Hmrd9/QyNYJFMgW3brWJyYY26y1YSc=
